config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registration"}

  resources :tags

  resources :categories

  resources :comments

  resources :posts

  get 'search' => 'posts#search'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  apply_simple_captcha

  validates :text, presence: true
  validates :user_name, presence: true
  validates :post_id, presence: true

  enum status: {accepting: 0, declining: 1, removal: 2}

end

app/controllers/comments_controller.rb
class CommentsController < AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:create]
  before_action :check_admin, except: [:create]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find comment_params[:post_id]
    @comment.user = current_user unless current_user.nil?

    res = current_user ? @comment.save : @comment.save_with_captcha
    respond_to do |format|
      if res
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @post, notice: 'Error!' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :user_id, :user_name, :post_id, :status, :captcha, :captcha_key)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :text
    = f.association :user, label_method: :email
    = f.input :user_name
    = f.association :post, label_method: :caption
    = f.input :status

  .form-actions
    = f.button :submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table.table
  thead
    tr
      th Text
      th User
      th User name
      th Post
      th Status
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.text
        td = comment.user_id
        td = comment.user_name
        td = comment.post_id
        td = comment.status
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Text:
  = @comment.text
p
  strong User:
  = @comment.user_id
p
  strong User name:
  = @comment.user_name
p
  strong Post:
  = @comment.post_id
p
  strong Status:
  = @comment.status

= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path