config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registration"}

  resources :tags

  resources :categories

  resources :comments

  resources :posts

  get 'search' => 'posts#search'

  root 'posts#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates :name, presence: true, length: {in: 2..255}, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < AdminController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # before_action :authenticate_user!
  #
  # before_action :check_admin

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end

    # def check_admin
    #   render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false) unless current_user.admin?(current_user)
    # end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= simple_form_for(@tag) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

= link_to 'Show', @tag
'|
= link_to 'Back', tags_path

app/views/tags/index.html.slim
h1 Listing tags

table.table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.slim
p#notice = notice

p
  strong Name:
  = @tag.name

= link_to 'Edit', edit_tag_path(@tag)
'|
= link_to 'Back', tags_path