config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registration"}

  resources :tags

  resources :categories

  resources :comments

  resources :posts

  get 'search' => 'posts#search'

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 10
  belongs_to :category
  has_many :comments
  has_and_belongs_to_many :tags

  validates_associated :tags

  validates :caption, presence: true, length: {in: 2..255}, uniqueness: true
  validates :article, presence: true
  validates :category_id, presence: true

  scope :category, -> (category_id) {where category_id: category_id}
  scope :tags, -> (tag_ids) {where('tag_id in (?)', tag_ids).joins(:tags)}
  scope :category_tags, -> (tag_ids, category_id) {
      where('tag_id in (?) and category_id = ?', tag_ids, category_id).joins(:tags) }


  def self.new_with_tag (params, tags_new)
    @post = Post.new(params)
    unless tags_new.nil?
      tags_new.split(',').each do |tag|
        @post.tags << Tag.create(name: tag.strip)
      end
    end
    @post
  end

  def self.update_with_tag (post, params, tags_new)
    post.update(params)
    unless tags_new.nil?
      tags_new.split(',').each do |tag|
        post.tags << Tag.create(name: tag.strip)
      end
    end
    post.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show, :search]


  # GET /posts
  # GET /posts.json
  def index
    sort = :desc
    sort = :asc if params[:sort] == 'asc'

    @posts = Post.order(created_at: sort).page(params[:page])

    @posts = Post.category_tags(params[:tag_ids], params[:category_id])
                 .order(created_at: :desc).page(params[:page]) if params[:tag_ids].present? and params[:category_id].present?

    @posts = Post.tags(params[:tag_ids])
                 .order(created_at: :desc).page(params[:page]) if params[:tag_ids].present? and not params[:category_id].present?

    @posts = Post.category(params[:category_id])
                 .order(created_at: :desc).page(params[:page]) if not params[:tag_ids].present? and params[:category_id].present?
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new_with_tag(post_params, params[:post][:new_tag])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if Post.update_with_tag(@post, post_params, params[:post][:new_tag])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    search = '%' + params[:search] + '%'
    @posts = Post.where('caption like ? or article like ?', search, search) if params[:search].present?
    @search = params[:search]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :article, :category_id, :tag_ids => [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_filter.html.slim
.row
  .col-xs-10.col-md-10
    =form_tag(posts_path, method: "get") do
      div
        = label_tag :sort, 'Sort by date'
        = select_tag :sort, options_for_select([['sort desc', 'desc'], ['sort asc', 'asc']], params[:sort])
      div
        = label_tag :category_id, 'Category'
        = select_tag(:category_id, options_from_collection_for_select(Category.all, :id, :name), {include_blank: 'None'})
      div
        label Tags:
        - Tag.all.each do |tag|
          = check_box_tag("tag_ids[]", tag.id)
          = label_tag tag.name

      = submit_tag 'Filter'

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :caption
    = f.input :article
    = f.association :category
    = f.association :tags, as: :check_boxes

    label for="new_tag" Новые теги
    input#new_tag type="text" name="post[new_tag]"

  .form-actions
    = f.button :submit, :class => 'btn btn-default'

app/views/posts/_search_from.html.slim
.row
  .col-xs-10.col-md-10
    =form_tag(search_path, method: 'get') do
      = label_tag :search, 'Search'
      = text_field_tag(:search)
      = submit_tag 'Search'

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
= render 'search_from'
= render 'filter'

h1 Listing posts

table.table
  thead
    tr
      th Caption
      th Article
      th Category
      th Tags
      th Date
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = link_to post.caption, post
        td = post.article
        td = post.category.name
        td = post.tags.map{|v| v.name}.join ', '
        td = post.created_at.strftime('%F %T')
        - if current_user && current_user.admin?(current_user)
          td = link_to 'Edit', edit_post_path(post)
        - if current_user && current_user.admin?(current_user)
          td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

br


.row
  .col-xs-12.col-md-12
    = paginate @posts

- if current_user && current_user.admin?(current_user)
  = link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/search.html.slim
- if @posts.nil? or @posts.size == 0
  p no result
- else
  - @posts.each do |post|
    div
      p
        strong Caption:
        = link_to (sanitize post.caption.gsub(@search, '<b>'+@search+'</b>'), tags: %w(b)), post_path(post)
      p
        strong Article:
        = sanitize post.article.gsub(@search, '<b>'+@search+'</b>'), tags: %w(b)

app/views/posts/show.html.slim
p#notice = notice

p
  strong Caption:
  = @post.caption
p
  strong Article:
  = @post.article
p
  strong Category:
  = @post.category.name
p
  strong Tags:
  = @post.tags.map{|v| v.name}.join ', '

p
  strong Comments:
  - @post.comments.each do |comment|
    p
      strong Name:
      = comment.text


= simple_form_for(Comment.new) do |f|
  = f.error_notification

  .form-inputs
    - if current_user
      = f.input :user_name, :input_html => {:value => current_user.email}
    - else
      = f.input :user_name
    = f.input :text
    - if not current_user
      = show_simple_captcha(:object=>'comment')
    /= f.association :post, label_method: :caption
    = f.input :post_id, :as => :hidden, :input_html => {:value => @post.id}

  .form-actions
    = f.button :submit

- if current_user && current_user.admin?(current_user)
  = link_to 'Edit', edit_post_path(@post)
  '|
= link_to 'Back', posts_path