config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registration"}

  resources :tags

  resources :categories

  resources :comments

  resources :posts

  get 'search' => 'posts#search'

  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  belongs_to :parent, class_name: "Category"
  has_many :children, class_name: "Category", foreign_key: "parent_id"

  validates :name, presence: true, length: {in: 2..255}, uniqueness: true

  def parent_name
    parent.try(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :parent

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table.table
  thead
    tr
      th Name
      th Parent
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = category.parent_name
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name
p
  strong Parent:
  = @category.parent_id

p
  strong Parent:
  = @category.parent_name

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path